/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_schamber;

/**
 *
 * @author scham
 */
public class interfacejeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfacejeu.class.getName());

    /**
     * Creates new form interfacejeu
     */
    public interfacejeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttontester = new javax.swing.JButton();
        Buttonrecommencer = new javax.swing.JButton();
        Nbexact = new javax.swing.JLabel();
        Nbhaut = new javax.swing.JLabel();
        Nbbas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tentative = new javax.swing.JLabel();
        vartentative = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonplus1 = new javax.swing.JButton();
        buttonplus2 = new javax.swing.JButton();
        buttonplus4 = new javax.swing.JButton();
        buttonplus3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        nb1 = new javax.swing.JLabel();
        nb2 = new javax.swing.JLabel();
        nb3 = new javax.swing.JLabel();
        nb4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        buttonmoins1 = new javax.swing.JButton();
        buttonmoins2 = new javax.swing.JButton();
        buttonmoins3 = new javax.swing.JButton();
        buttonmoins4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Trouver le bon code en moins de 5 tentatives !");

        buttontester.setText("Tester");

        Buttonrecommencer.setText("Recommencer");

        Nbexact.setText("Nombre de chiffres exacts : ");

        Nbhaut.setText("Nombre de chiffres trop haut : ");

        Nbbas.setText("Nombre de chiffres trop bas :");

        jLabel5.setText("0");

        jLabel6.setText("0");

        jLabel7.setText("0");

        tentative.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        tentative.setText("Tentatives :");

        vartentative.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        vartentative.setText("0 / 5");

        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 5, 5));

        buttonplus1.setText("/\\");
            jPanel3.add(buttonplus1);

            buttonplus2.setText("/\\");
                jPanel3.add(buttonplus2);

                buttonplus4.setText("/\\");
                    jPanel3.add(buttonplus4);

                    buttonplus3.setText("/\\");
                        jPanel3.add(buttonplus3);

                        jPanel4.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

                        nb1.setText("nb1");
                        nb1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 3, true));
                        jPanel4.add(nb1);

                        nb2.setText("nb2");
                        nb2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 3, true));
                        jPanel4.add(nb2);

                        nb3.setText("nb3");
                        nb3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 3, true));
                        jPanel4.add(nb3);

                        nb4.setText("nb4");
                        nb4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 3, true));
                        jPanel4.add(nb4);

                        jPanel5.setLayout(new java.awt.GridLayout(1, 4, 5, 0));

                        buttonmoins1.setText("\\/");
                        buttonmoins1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonmoins1ActionPerformed(evt);
                            }
                        });
                        jPanel5.add(buttonmoins1);

                        buttonmoins2.setText("\\/");
                        buttonmoins2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonmoins2ActionPerformed(evt);
                            }
                        });
                        jPanel5.add(buttonmoins2);

                        buttonmoins3.setText("\\/");
                        buttonmoins3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonmoins3ActionPerformed(evt);
                            }
                        });
                        jPanel5.add(buttonmoins3);

                        buttonmoins4.setText("\\/");
                        buttonmoins4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonmoins4ActionPerformed(evt);
                            }
                        });
                        jPanel5.add(buttonmoins4);

                        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                        jPanel2.setLayout(jPanel2Layout);
                        jPanel2Layout.setHorizontalGroup(
                            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        );
                        jPanel2Layout.setVerticalGroup(
                            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        );

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Nbexact, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(135, 135, 135)
                                                        .addComponent(tentative))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(51, 51, 51)
                                                        .addComponent(buttontester, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Nbhaut, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Nbbas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(152, 152, 152)
                                                        .addComponent(vartentative, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(Buttonrecommencer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(26, Short.MAX_VALUE))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(buttontester)))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Nbexact)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tentative, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nbhaut)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Nbbas)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(vartentative, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Buttonrecommencer)
                                .addGap(58, 58, 58))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void buttonmoins3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmoins3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonmoins3ActionPerformed

    private void buttonmoins4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmoins4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonmoins4ActionPerformed

    private void buttonmoins2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmoins2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonmoins2ActionPerformed

    private void buttonmoins1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmoins1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonmoins1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfacejeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonrecommencer;
    private javax.swing.JLabel Nbbas;
    private javax.swing.JLabel Nbexact;
    private javax.swing.JLabel Nbhaut;
    private javax.swing.JButton buttonmoins1;
    private javax.swing.JButton buttonmoins2;
    private javax.swing.JButton buttonmoins3;
    private javax.swing.JButton buttonmoins4;
    private javax.swing.JButton buttonplus1;
    private javax.swing.JButton buttonplus2;
    private javax.swing.JButton buttonplus3;
    private javax.swing.JButton buttonplus4;
    private javax.swing.JButton buttontester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel nb1;
    private javax.swing.JLabel nb2;
    private javax.swing.JLabel nb3;
    private javax.swing.JLabel nb4;
    private javax.swing.JLabel tentative;
    private javax.swing.JLabel vartentative;
    // End of variables declaration//GEN-END:variables
}
