/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.ArrayList;

/**
 *
 * @author scham
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    // --- Étape 4 : Attributs du quiz ---
    private ArrayList<Question> questions = new ArrayList<>();
    private int indexQuestionCourante = 0;
    private int score = 0;

    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();

        // --- Création des questions ---
        questions.add(new Question(
            "Quelle est la capitale de la France ?",
            "Lyon", "Paris", "Marseille", "Nice", 2
        ));
        questions.add(new Question(
            "Combien font 6 × 7 ?",
            "42", "36", "49", "40", 1
        ));
        questions.add(new Question(
            "Quel est l’élément chimique O ?",
            "Or", "Oxygène", "Ozone", "Osmium", 2
        ));
        questions.add(new Question(
            "Quelle couleur obtient-on en mélangeant bleu et jaune ?",
            "Rouge", "Vert", "Violet", "Orange", 2
        ));
        questions.add(new Question(
            "Combien de jours dans une année bissextile ?",
            "364", "365", "366", "367", 3
        ));

        // Afficher la première question
        afficherQuestionCourante();
    }

    // --- Étape 4 : Méthode pour afficher la question courante ---
    private void afficherQuestionCourante() {
        // Récupère la question courante
        Question q = questions.get(indexQuestionCourante);

        // Mise à jour du texte
        jLabel1.setText(q.getIntitule());
        jButton1.setText(q.getProposition1());
        jButton2.setText(q.getProposition2());
        jButton3.setText(q.getProposition3());
        jButton4.setText(q.getProposition4());

        // Efface le message précédent
        jLabel2.setText("");

        // Réactive tous les boutons
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
    }

    // --- Étape 5 : Vérifier la réponse utilisateur ---
    private void verifierReponse(int choix) {
    // Récupérer la question courante
    Question q = questions.get(indexQuestionCourante);

    // Vérification
    if (choix == q.getIndexBonneReponse()) {
        jLabel2.setText("Bonne réponse !");
        score++;
    } else {
        jLabel2.setText("Mauvaise réponse...");
    }

    // Mettre à jour le label du score (format "Score : X / N")
    jLabelScore.setText("Score : " + score + " / " + questions.size());

    // Désactiver tous les boutons de réponse
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabelScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 36, 380, 54));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 161, 85, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 161, 87, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 161, 87, -1));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 161, 87, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 233, 283, -1));

        jButton5.setText("Question suivante ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 271, -1, -1));

        jLabelScore.setText("Score : 0 / 5");
        getContentPane().add(jLabelScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 10, 84, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        verifierReponse(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       verifierReponse(4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        indexQuestionCourante++;

        if (indexQuestionCourante < questions.size()) {
            afficherQuestionCourante();
            // mise à jour du score (déjà faite dans afficherQuestionCourante mais on peut rappeler)
            jLabelScore.setText("Score : " + score + " / " + questions.size());
        } else {
            // Fin du quiz
            jLabel1.setText("Quiz terminé !");
            jLabel2.setText("Score final : " + score + " / " + questions.size());

            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);

            jButton5.setEnabled(false);
        }
    
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelScore;
    // End of variables declaration//GEN-END:variables
}
